# Generated by Django 5.2.1 on 2025-05-25 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.CharField(max_length=255)),
                ('fonte', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('dataHoraPublicacao', models.DateTimeField()),
                ('dataHoraAdicao', models.DateTimeField(auto_now=True)),
                ('colaborador', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria')),
            ],
        ),
    ]
