# Generated by Django 5.2.1 on 2025-05-25 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_remove_categoria_id_alter_categoria_nome'),
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.URLField(),
        ),
    ]
